[programs.localnet]
mysolanaapp = "Cd5pKiQtUusXou6shdYHzKKnpnyYG5Q2jPPd51ESfWCr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/florian/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
